INSERT INTO agency (name) VALUES ('Department of Education');
INSERT INTO agency (name, acronym) VALUES ('Department of Transportation', 'FDOT');
INSERT INTO agency (name, acronym) VALUES ('Children and Families', 'DCF');
INSERT INTO agency (name, acronym) VALUES ('Office of Insurance Regulation', 'OIR');
INSERT INTO agency (name, acronym) VALUES ('Justice Administrative Commission', 'JAC');
INSERT INTO agency (name, acronym) VALUES ('Agency for Health Care Administration', 'AHCA');
INSERT INTO agency (name) VALUES ('State Courts System');
INSERT INTO agency (name, acronym) VALUES ('Department of Health', 'DOH');
INSERT INTO agency (name, acronym) VALUES ('Agency for Persons with Disabilities', 'APD');
INSERT INTO agency (name) VALUES ('Veterans Affairs');
INSERT INTO agency (name) VALUES ('Commerce');
INSERT INTO agency (name) VALUES ('Florida Legislature');
INSERT INTO agency (name, acronym) VALUES ('Business and Professional Regulations', 'DBPR');
INSERT INTO agency (name, acronym) VALUES ('Department of Corrections', 'FDC');
INSERT INTO agency (name) VALUES ('Military Affairs');
INSERT INTO agency (name, acronym) VALUES ('Environmental Protection', 'DEP');
INSERT INTO agency (name) VALUES ('Office of the Attorney General');
INSERT INTO agency (name, acronym) VALUES ('Department of State', 'DOS');
INSERT INTO agency (name) VALUES ('Agriculture and Consumer Services');
INSERT INTO agency (name, acronym) VALUES ('Management Services', 'DMS');
INSERT INTO agency (name, acronym) VALUES ('Florida Fish and Wildlife Conservation Commission', 'FWC');
INSERT INTO agency (name, acronym) VALUES ('Juvenile Justice', 'DJJ');
INSERT INTO agency (name, acronym) VALUES ('Elder Affairs', 'DOEA');
INSERT INTO agency (name) VALUES ('Financial Services');
INSERT INTO agency (name, acronym) VALUES ('Department of Law Enforcement', 'FDLE');
INSERT INTO agency (name, acronym) VALUES ('Department of Revenue', 'DOR');
INSERT INTO agency (name, acronym) VALUES ('Commission on Offender Review', 'FCOR');
INSERT INTO agency (name, acronym) VALUES ('Division of Emergency Management', 'FDEM');
INSERT INTO agency (name, acronym) VALUES ('Public Service Commission', 'PSC');
INSERT INTO agency (name, acronym) VALUES ('Florida Board of Governors', 'FLBOG');
INSERT INTO agency (name, acronym) VALUES ('School for the Deaf & Blind', 'FSDB');
INSERT INTO agency (name) VALUES ('Department of Lottery');
INSERT INTO agency (name, acronym) VALUES ('Florida Gaming Control Commission', 'FGCC');
INSERT INTO agency (name, acronym) VALUES ('Office of Financial Regulation', 'OFR');
INSERT INTO agency (name, acronym) VALUES ('Highway Safety and Motor Vehicle', 'DHSMV');
INSERT INTO agency (name, acronym) VALUES ('Florida Commission on Human Relations', 'FCHR');
INSERT INTO agency (name) VALUES ('Executive Office of the Governor');
INSERT INTO agency (name, acronym) VALUES ('Division of Administrative Hearings', 'DOAH')